apiVersion: v1
kind: Service
metadata:
  name: "consumer-app"
  namespace: "leaf-image-management-system"
spec:
  selector:
    name: "consumer-app"
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
