apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: consumer-app-backendconfig
  namespace: leaf-image-management-system
spec:
  healthCheck:
    requestPath: /ping
    port: 8000
    type: HTTP
